package se.good_omens.relicCruncher;

import java.util.HashMap;

public class EnemyLocations {
	private HashMap<String, EnemyLocation> enemyLocations = new HashMap<String, EnemyLocation>();

	public EnemyLocations() {
		for(String lineData : rawData) {
			String[] parts = lineData.split("\\;");
			enemyLocations.put(parts[0].toLowerCase().trim(), new EnemyLocation(parts[0], parts[1], parts[2], parts[3]));
		}
	}
	
	public String getEnemyLocation(String enemyName) {
		EnemyLocation el = enemyLocations.get(enemyName.toLowerCase().trim());
		if(el != null) {
			return enemyLocations.get(enemyName.toLowerCase()).toString();
		} else {
			return " "+ enemyName +" in an Unknown Location.";
		}
	}
	
	private String[] rawData = {
			"002-ER;The Index;None;Neptune;",
			"Alad V;Assassination:Themisto;Corpus Gas City;Jupiter;",
			"Amalgam Alkonost;None;Corpus Gas City;Jupiter;",
			"Amalgam Arca Heqet;None;Corpus Gas City;Jupiter;",
			"Amalgam Arca Kucumatz;None;Corpus Gas City;Jupiter;",
			"Amalgam Cinder Machinist;None;Corpus Gas City;Jupiter;",
			"Amalgam Heqet;None;Corpus Gas City;Jupiter;",
			"Amalgam Kucumatz;None;Corpus Gas City;Jupiter;",
			"Amalgam Machinist;None;Corpus Gas City;Jupiter;",
			"Amalgam MOA;None;Corpus Gas City;Jupiter;",
			"Amalgam Osprey;None;Corpus Gas City;Jupiter;",
			"Amalgam Phase MOA;None;Corpus Gas City;Jupiter;",
			"Amalgam Satyr;None;Corpus Gas City;Jupiter;",
			"Amalgam Swarm Satyr;None;Corpus Gas City;Jupiter;",
			"Ambulas;Assassination:Hades;Corpus Outpost;Pluto;",
			"Armaments Director;Fortuna Bounty;Orb Vallis;Venus;",
			"Armis Ulta;The Index;None;Neptune;",
			"Attack Drone (Archwing Enemy);Archwing (Mission);Corpus Ship (Archwing);Venus:Phobos:Jupiter:Neptune;",
			"Auditor;The Index;None;Neptune;",
			"Aurax Actinic;Empyrean;None;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Aurax Atloc Raknoid;Empyrean;None;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Aurax Baculus;Empyrean;None;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Aurax Culveri MOA;Empyrean;None;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Aurax Polaris MOA;Empyrean;None;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Aurax Vertec;Empyrean;None;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Axio Basilisk;Empyrean;Free Space;Neptune Proxima;",
			"Axio Crewman;Empyrean;None;Neptune Proxima;",
			"Axio Crewship;Empyrean;Free Space;Neptune Proxima;",
			"Axio Detron Crewman;Empyrean;None;Neptune Proxima;",
			"Axio Disc MOA;Empyrean;None;Neptune Proxima;",
			"Axio Elite Crewman;Empyrean;None;Neptune Proxima;",
			"Axio Engineer;Empyrean:Volatile;None;Neptune Proxima;",
			"Axio Gox;Empyrean;Free Space;Neptune Proxima;",
			"Axio Harpi;Empyrean;Free Space;Neptune Proxima;",
			"Axio MOA;Empyrean;None;Neptune Proxima;",
			"Axio Nullifier Crewman;Empyrean;None;Neptune Proxima;",
			"Axio Numon;Empyrean;None;Neptune Proxima;",
			"Axio Pilot;Empyrean;None;Neptune Proxima;",
			"Axio Railgun MOA;Empyrean;None;Neptune Proxima;",
			"Axio Ranger Crewman;Empyrean;None;Neptune Proxima;",
			"Axio Shield Osprey;Empyrean;None;Neptune Proxima;",
			"Axio Shockwave MOA;Empyrean;None;Neptune Proxima;",
			"Axio Stropha Crewman;Empyrean;None;Neptune Proxima;",
			"Axio Tech;Empyrean;None;Neptune Proxima;",
			"Axio Vambac;Empyrean;None;Neptune Proxima;",
			"Axio Weaver;Empyrean;Free Space;Neptune Proxima;",
			"Axio Zerca;Empyrean;None;Neptune Proxima;",
			"Azoth;The Index;None;Neptune;",
			"Cannon Battery (Corpus);Empyrean;Free Space;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Carrier;Archwing (Mission);None;None;",
			"Cinderthresh Hyena;Fortuna Bounty;Orb Vallis;Venus;",
			"Coildrive;Orb Vallis;None;Venus;",
			"Comet Shard;Empyrean;Free Space;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Condor Dropship;None;Corpus Ice Planet:Corpus Outpost:Orb Vallis;None;",
			"Condor Storm Dropship;Assassination:Hades;Corpus Outpost;Pluto;",
			"Coolant Raknoid;None;Orb Vallis;Venus;",
			"Corpus Cestra Target;Fortuna Bounty;Orb Vallis;Venus;",
			"Corpus Power Carrier;Excavation;Corpus Ice Planet:Corpus Outpost;None;",
			"Corpus Power Carrier (Orb Vallis);Fortuna Bounty;Orb Vallis;Venus;",
			"Corpus Ramsled;Empyrean;Free Space;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Corpus Sniper Target;Fortuna Bounty;Orb Vallis;Venus;",
			"Corpus Supra Target;Fortuna Bounty;Orb Vallis;Venus;",
			"Corpus Target;Capture;None;None;",
			"Corpus Tech;None;None;Venus:Earth:Mars:Jupiter:Neptune:Pluto:Eris:Europa;",
			"Corpus Trencher Target;Fortuna Bounty;Orb Vallis;Venus;",
			"Corpus Warden;Rescue;None;None;",
			"Corvette;Archwing (Mission);None;None;",
			"Cryo Sentry;Empyrean;None;None;",
			"Datalyst;Operation: Shadow Debt;None;None;",
			"Demolisher Anti MOA;Disruption;Corpus Ship:Orokin Moon;Neptune:Lua;",
			"Demolisher Bursa;Disruption;Corpus Ship:Orokin Moon;Neptune:Lua;",
			"Demolisher Hyena;Disruption;Corpus Ship:Orokin Moon;Neptune:Lua;",
			"Demolisher Machinist;Disruption;Corpus Ship:Orokin Moon;Neptune:Lua;",
			"Demolyst;None;Corpus Gas City;Jupiter;",
			"Demolyst Heqet;Disruption;Corpus Gas City;Jupiter;",
			"Demolyst Machinist;Disruption;Corpus Gas City;Jupiter;",
			"Demolyst MOA;Disruption;Corpus Gas City;Jupiter;",
			"Demolyst Osprey;None;Corpus Gas City;Jupiter;",
			"Demolyst Satyr;Disruption;Corpus Gas City;Jupiter;",
			"Derim Zahn;The Index;None;Neptune;",
			"Derivator Crewman;None;Zariman (Tileset);Zariman Ten Zero;",
			"Dru Pesfor;The Index;None;Neptune;",
			"Elite Axio Basilisk;Empyrean;Free Space;Neptune Proxima;",
			"Elite Axio Harpi;Empyrean;Free Space;Neptune Proxima;",
			"Elite Axio Weaver;Empyrean;Free Space;Neptune;",
			"Elite Orm Basilisk;Empyrean;Free Space;Veil Proxima;",
			"Elite Orm Harpi;Empyrean;Free Space;Veil Proxima;",
			"Elite Orm Weaver;Empyrean;Free Space;Veil Proxima;",
			"Elite Taro Basilisk;Empyrean;Free Space;Venus Proxima;",
			"Elite Taro Harpi;Empyrean;Free Space;Venus Proxima;",
			"Elite Taro Weaver;Empyrean;Free Space;Venus Proxima;",
			"Elite Vorac Basilisk;Empyrean;Free Space;Pluto Proxima;",
			"Elite Vorac Harpi;Empyrean;Free Space;Pluto Proxima;",
			"Elite Vorac Weaver;Empyrean;Free Space;Pluto Proxima;",
			"Errant Specter;Granum Void;Corpus Ship;None;",
			"Exploiter Orb;Fortuna Bounty;Orb Vallis;Venus;",
			"Frigate;Archwing (Mission);Corpus Ship (Archwing);Venus:Mars:Jupiter:Neptune;",
			"Gox;Archwing (Mission);Corpus Ship (Archwing);None;",
			"Gyre Hyena;Fortuna Bounty;Orb Vallis;Venus;",
			"Hyena Ln2;Assassination:Psamathe;Corpus Ship;Neptune;",
			"Hyena Ng;Assassination:Psamathe;Corpus Ship;Neptune;",
			"Hyena Pb;Assassination:Psamathe;Corpus Ship;Neptune;",
			"Hyena Th;Assassination:Psamathe;Corpus Ship;Neptune;",
			"Icemire Hyena;Fortuna Bounty;Orb Vallis;Venus;",
			"Jackal;Assassination:Fossa;Corpus Ship;Venus;",
			"Jad Teran;The Index;None;Neptune;",
			"Jen Dro;The Index;None;Neptune;",
			"Juno Crewman;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Dera MOA;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Disc MOA;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Elite Crewman;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Fog Comba;None;Corpus Ship;None;",
			"Juno Geminex MOA;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Glaxion MOA;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Jactus Osprey;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Malleus Machinist;None;Corpus Ship;None;",
			"Juno Nul Comba;None;Corpus Ship;None;",
			"Juno Nullifier Crewman;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Oxium Osprey;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Sap Comba;None;Corpus Ship;None;",
			"Juno Sapper MOA;Brutus:Ascension;Stalker's Lair;None;",
			"Juno Shield Osprey;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Slo Comba;None;Corpus Ship;None;",
			"Juno Sniper Crewman;None;Corpus Ship:Zariman (Tileset);None;",
			"Juno Tech;None;Corpus Ship:Zariman (Tileset);None;",
			"Kyta Raknoid;None;Orb Vallis;Venus;",
			"Latrox Une;Necralisk Bounty;Cambion Drift;Deimos;",
			"Lockjaw & Sol;The Index;None;Neptune;",
			"Locust Drone;Archwing (Mission);Corpus Ship (Archwing);None;",
			"Lynx;Orokin Sabotage:Help Clem:Grineer Spy;None;None;",
			"Lynx Osprey;Orokin Sabotage:Help Clem:Grineer Spy;None;None;",
			"Lynx Turret;Orokin Sabotage:Help Clem:Grineer Spy;None;None;",
			"Machinist;None;Corpus Gas City;Jupiter;",
			"Minima MOA;None;Corpus Ship:Zariman (Tileset);None;",
			"Mite Raknoid;None;Orb Vallis;Venus;",
			"MOA;None;None;Venus:Mars:Neptune:Pluto:Europa;",
			"M-W.A.M.;The Index;None;Neptune;",
			"Nako Xol;The Index;None;Neptune;",
			"Nemes Ranger;Archwing (Mission);Corpus Ship (Archwing);None;",
			"Nemes Rt;Assassination:Naamah;Corpus Ice Planet;Europa;",
			"Nemes Scout;Archwing (Mission);Corpus Ship (Archwing);None;",
			"Nullifier Target;Capture;None;None;",
			"Optio;Empyrean;None;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Orm Basilisk;Empyrean;Free Space;Veil Proxima;",
			"Orm Crewman;Empyrean;None;Veil Proxima;",
			"Orm Crewship;Empyrean;Free Space;Veil Proxima;",
			"Orm Detron Crewman;Empyrean;None;Veil Proxima;",
			"Orm Disc MOA;Empyrean;None;Veil Proxima;",
			"Orm Elite Crewman;Empyrean;None;Veil Proxima;",
			"Orm Engineer;Empyrean:Volatile;None;Veil Proxima;",
			"Orm Gox;Empyrean;Free Space;Veil Proxima;",
			"Orm Harpi;Empyrean;Free Space;Veil Proxima;",
			"Orm MOA;Empyrean;None;Veil Proxima;",
			"Orm Nullifier Crewman;Empyrean;None;Veil Proxima;",
			"Orm Numon;Empyrean;None;Veil Proxima;",
			"Orm Pilot;Empyrean;None;Veil Proxima;",
			"Orm Railgun MOA;Empyrean;None;Veil Proxima;",
			"Orm Ranger Crewman;Empyrean;None;Veil Proxima;",
			"Orm Shield Osprey;Empyrean;None;Veil Proxima;",
			"Orm Shockwave MOA;Empyrean;None;Veil Proxima;",
			"Orm Stropha Crewman;Empyrean;None;Veil Proxima;",
			"Orm Tech;Empyrean;None;Veil Proxima;",
			"Orm Vambac;Empyrean;None;Veil Proxima;",
			"Orm Weaver;Empyrean;Free Space;Veil Proxima;",
			"Orm Zerca;Empyrean;None;Veil Proxima;",
			"Pelna Cade;The Index;None;Neptune;",
			"Penta Ranger;Archwing (Mission);Corpus Ship (Archwing);None;",
			"Profit-Taker Orb;Fortuna Bounty;Orb Vallis;Venus;",
			"Protea Specter;The Deadlock Protocol;None;None;",
			"Quanta Ranger;Archwing (Mission);Corpus Ship (Archwing);None;",
			"Rabbleback Hyena;Fortuna Bounty;Orb Vallis;Venus;",
			"Rana Del;The Index;None;Neptune;",
			"Ranger;Archwing (Mission);Corpus Ship (Archwing);None;",
			"Raptor Mt;Assassination:Naamah;Corpus Ice Planet;Europa;",
			"Raptor Ns;Assassination:Naamah;Corpus Ice Planet;Europa;",
			"Raptor Rv;Assassination:Naamah;Corpus Ice Planet;Europa;",
			"Raptor RX;The Index;None;Neptune;",
			"Razorback;Razorback Armada;Corpus Ship;None;",
			"Remech Osprey;Assassination:Hades;Corpus Outpost;Pluto;",
			"Scyto Raknoid;None;Orb Vallis;Venus;",
			"Senta Turret (Orb Vallis);None;Orb Vallis;Venus;",
			"Sentient Research Director;Fortuna Bounty;Orb Vallis;Venus;",
			"Sniper Crewman;None;None;Earth:Mars:Jupiter:Neptune:Pluto:Eris:Europa;",
			"Specter Particles;Granum Void;Corpus Ship;None;",
			"Spectralyst;None;Corpus Gas City;Jupiter;",
			"Tarask Bursa;Empyrean;None;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Taro Basilisk;Empyrean;Free Space;Venus Proxima;",
			"Taro Crewman;Empyrean;None;Venus Proxima;",
			"Taro Crewship;Empyrean;Free Space;Venus Proxima;",
			"Taro Detron Crewman;Empyrean;None;Venus Proxima;",
			"Taro Disc MOA;Empyrean;None;Venus Proxima;",
			"Taro Elite Crewman;Empyrean;None;Venus Proxima;",
			"Taro Engineer;Empyrean:Volatile;None;Venus Proxima;",
			"Taro Gox;Empyrean;Free Space;Venus Proxima;",
			"Taro Harpi;Empyrean;Free Space;Venus Proxima;",
			"Taro MOA;Empyrean;None;Venus Proxima;",
			"Taro Nullifier Crewman;Empyrean;None;Venus Proxima;",
			"Taro Numon;Empyrean;None;Venus Proxima;",
			"Taro Pilot;Empyrean;None;Venus Proxima;",
			"Taro Railgun MOA;Empyrean;None;Venus Proxima;",
			"Taro Ranger Crewman;Empyrean;None;Venus Proxima;",
			"Taro Secura Osprey;Empyrean;None;Venus Proxima;",
			"Taro Shockwave MOA;Empyrean;None;Venus Proxima;",
			"Taro Stropha Crewman;Empyrean;None;Venus Proxima;",
			"Taro Tech;Empyrean;None;Venus Proxima;",
			"Taro Vambac;Empyrean;None;Venus Proxima;",
			"Taro Weaver;Empyrean;Free Space;Venus Proxima;",
			"Taro Zerca;Empyrean;None;Venus Proxima;",
			"Terra Ambulas;None;Orb Vallis;Venus;",
			"Terra Attack Drone;None;Orb Vallis;Venus;",
			"Terra Auto Turret;None;Orb Vallis;Venus;",
			"Terra Crewman;None;Orb Vallis;Venus;",
			"Terra Elite Crewman;None;Orb Vallis;Venus;",
			"Terra Elite Embattor MOA;None;Orb Vallis;Venus;",
			"Terra Elite Overtaker;None;Orb Vallis;Venus;",
			"Terra Elite Provisor;None;Orb Vallis;Venus;",
			"Terra Elite Raptor Sx;None;Orb Vallis;Venus;",
			"Terra Elite Trencher;None;Orb Vallis;Venus;",
			"Terra Embattor MOA;None;Orb Vallis;Venus;",
			"Terra Jackal;None;Orb Vallis;Venus;",
			"Terra Jailer;Orb Vallis Bounty;Orb Vallis;Venus;",
			"Terra Manker;Profit-Taker Bounty;Orb Vallis;Venus;",
			"Terra MOA;None;Orb Vallis;Venus;",
			"Terra Overtaker;None;Orb Vallis;Venus;",
			"Terra Plasmor Crewman;None;Orb Vallis;Venus;",
			"Terra Provisor;None;Orb Vallis;Venus;",
			"Terra Raptor SX;None;Orb Vallis;Venus;",
			"Terra Rocket Turret;None;Orb Vallis;Venus;",
			"Terra Shield Osprey;None;Orb Vallis;Venus;",
			"Terra Shockwave MOA;None;Orb Vallis;Venus;",
			"Terra Sniper Crewman;None;Orb Vallis;Venus;",
			"Terra Trencher;None;Orb Vallis;Venus;",
			"The Raptor;Assassination:Naamah;Corpus Ice Planet;Europa;",
			"The Sergeant;Iliad;Corpus Ship;Phobos;",
			"Thermic Raknoid;Thermia Fractures;Orb Vallis;Venus;",
			"Tia Mayn;The Index;None;Neptune;",
			"Treasurer;None;Corpus Ship;None;",
			"Vallis Surveillance Drone;Fortuna Bounty;Orb Vallis;Venus;",
			"Vapos Anti MOA;None;Corpus Gas City;Jupiter;",
			"Vapos Aquila;None;Corpus Gas City;Jupiter;",
			"Vapos Bioengineer;None;Corpus Gas City;Jupiter;",
			"Vapos Condor Dropship;None;Corpus Gas City;Jupiter;",
			"Vapos Condor Elite Dropship;None;Corpus Gas City;Jupiter;",
			"Vapos Crewman;None;Corpus Gas City;Jupiter;",
			"Vapos Detron Crewman;None;Corpus Gas City;Jupiter;",
			"Vapos Detron Ranger;None;Corpus Gas City;Jupiter;",
			"Vapos Elite Crewman;None;Corpus Gas City;Jupiter;",
			"Vapos Elite Ranger;None;Corpus Gas City;Jupiter;",
			"Vapos Fusion MOA;None;Corpus Gas City;Jupiter;",
			"Vapos MOA;None;Corpus Gas City;Jupiter;",
			"Vapos Nullifier;None;Corpus Gas City;Jupiter;",
			"Vapos Nullifier Ranger;None;Corpus Gas City;Jupiter;",
			"Vapos Oxium Osprey;None;Corpus Gas City;Jupiter;",
			"Vapos Prod Crewman;None;Corpus Gas City;Jupiter;",
			"Vapos Railgun MOA;None;Corpus Gas City;Jupiter;",
			"Vapos Sapping Osprey;None;Corpus Gas City;Jupiter;",
			"Vapos Shield Osprey;None;Corpus Gas City;Jupiter;",
			"Vapos Shockwave MOA;None;Corpus Gas City;Jupiter;",
			"Vapos Sniper Crewman;None;Corpus Gas City;Jupiter;",
			"Vapos Sniper Ranger;None;Corpus Gas City;Jupiter;",
			"Vapos Tech;None;Corpus Gas City;Jupiter;",
			"Vapos Tech Ranger;None;Corpus Gas City;Jupiter;",
			"Ved Xol;The Index;None;Neptune;",
			"Vivisect Director;Fortuna Bounty;Orb Vallis;Venus;",
			"Vorac Basilisk;Empyrean;Free Space;Pluto Proxima;",
			"Vorac Crewman;Empyrean;None;Pluto Proxima;",
			"Vorac Crewship;Empyrean;Free Space;Pluto Proxima;",
			"Vorac Detron Crewman;Empyrean;None;Pluto Proxima;",
			"Vorac Disc MOA;Empyrean;None;Pluto Proxima;",
			"Vorac Elite Crewman;Empyrean;None;Pluto Proxima;",
			"Vorac Engineer;Empyrean:Volatile;None;Pluto Proxima;",
			"Vorac Gox;Empyrean;Free Space;Pluto Proxima;",
			"Vorac Harpi;Empyrean;Free Space;Pluto Proxima;",
			"Vorac MOA;Empyrean;None;Pluto Proxima;",
			"Vorac Nullifier Crewman;Empyrean;None;Pluto Proxima;",
			"Vorac Numon;Empyrean;None;Pluto Proxima;",
			"Vorac Pilot;Empyrean;None;Pluto Proxima;",
			"Vorac Railgun MOA;Empyrean;None;Pluto Proxima;",
			"Vorac Ranger Crewman;Empyrean;None;Pluto Proxima;",
			"Vorac Shield Osprey;Empyrean;None;Pluto Proxima;",
			"Vorac Shockwave MOA;Empyrean;None;Pluto Proxima;",
			"Vorac Stropha Crewman;Empyrean;None;Pluto Proxima;",
			"Vorac Tech;Empyrean;None;Pluto Proxima;",
			"Vorac Vambac;Empyrean;None;Pluto Proxima;",
			"Vorac Weaver;Empyrean;Free Space;Pluto Proxima;",
			"Vorac Zerca;Empyrean;None;Pluto Proxima;",
			"Zanuka;Assasination:Themisto;Corpus Gas City;Jupiter;",
			"Zanuka Hunter;Assassination:Themisto;None;None;","Corrupted Drahk;Conjunction Survival;Orokin Moon;Lua;",
			"Corrupted Drahk Master;Conjunction Survival;Orokin Moon;Lua;",
			"Corrupted Warden;Rescue;Orokin Moon;Lua;",
			"Ember Specter;Junction;None;Jupiter;",
			"Equinox Specter;Junction;None;Saturn;",
			"Excalibur Specter;Junction;None;Neptune;",
			"Feyarch Specter;The Silver Grove;Grineer Forest;Earth;",
			"Frost Specter;Junction;None;Uranus;",
			"Knave Specter;The Silver Grove;Grineer Forest;Earth;",
			"Loki Specter;Junction;None;Earth;",
			"Mag Specter;Junction;None;Mars;",
			"Mesa Specter;Junction;None;Pluto;",
			"Nova Specter;Junction;None;Jupiter;",
			"Orokin Sentry;None;Orokin Tower;Void;",
			"Orokin Spectator;Spy;Orokin Moon;Lua;",
			"Orphid Specter;The Silver Grove;Grineer Forest;Earth;",
			"Rhino Specter;Junction;None;Venus;",
			"Saryn Specter;Junction;None;Pluto;",
			"Trinity Specter;Junction;None;Mars;",
			"Valkyr Specter;Junction;None;Ceres;",
			"Volt Specter;Junction;None;Earth;","Aerial Commander;Cetus Bounties;Plains of Eidolon;Earth;",
			"Akkalak Turret;None;Plains of Eidolon;Earth;",
			"Arid Butcher;None;Grineer Settlement;Mars;",
			"Arid Eviscerator;None;Grineer Settlement;Mars;",
			"Arid Heavy Gunner;None;Grineer Settlement;Mars;",
			"Arid Hellion;None;Grineer Settlement;Mars;",
			"Arid Lancer;None;Grineer Settlement;Mars;",
			"Arid Seeker;None;Grineer Settlement;Mars;",
			"Arid Trooper;None;Grineer Settlement;Mars;",
			"Artificer;Operation: Shadow Debt;None;None;",
			"Armored Roller;Assassination:Merrow;Grineer Asteroid;Sedna;",
			"Bailiff;None;Grineer Asteroid Fortress;Kuva Fortress;",
			"Blite Captain;Empyrean;Grineer Galleon;Earth Proxima:Veil Proxima;",
			"Cannon Battery (Grineer);Empyrean;Free Space;Earth Proxima:Saturn Proxima:Veil Proxima;",
			"Captain Vor;Assassination:Tolstoj:Exta;Grineer Asteroid:Grineer Shipyard;Mercury:Ceres;",
			"Corrupted Vor;Level ≥40 Orokin Void missions:The Undercroft Exterminate;Orokin Tower:The Undercroft;Void;",
			"Councilor Vay Hek;Assassination:Oro;Grineer Forest;Earth;",
			"Darek Draga;None;Grineer Sealab;None;",
			"Dargyn;Archwing (Mission);Free Space;None;",
			"Dargyn Pilot;None;Plains of Eidolon;Earth;",
			"Demolisher Bailiff;Disruption;Grineer Settlement:Grineer Galleon:Grineer Asteroid Fortress;Mars:Sedna:Kuva Fortress;",
			"Demolisher Devourer;Disruption;Grineer Settlement;Mars;",
			"Demolisher Expired;Disruption;Grineer Settlement:Grineer Galleon;Mars:Sedna;",
			"Demolisher Heavy Gunner;Disruption;Grineer Settlement:Grineer Galleon:Grineer Asteroid Fortress;Mars:Sedna:Kuva Fortress;",
			"Demolisher Kuva Guardian;Disruption;Kuva Fortress;Kuva Fortress;",
			"Demolisher Nox;Disruption;Grineer Galleon:Grineer Asteroid Fortress;Sedna:Kuva Fortress;",
			"Disruptor Drone;The Law of Retribution;Grineer Forest:Grineer Shipyard:Grineer Settlement;Earth:Ceres:Mars;",
			"Draga;None;Grineer Sealab;None;",
			"Dreg;Archwing (Mission);None;None;",
			"Drekar Ballista;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Butcher;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Elite Lancer;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Eviscerator;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Heavy Gunner;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Hellion;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Lancer;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Manic;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Manic Bombard;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Scorpion;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Seeker;None;Grineer Sealab;Earth:Uranus;",
			"Drekar Trooper;None;Grineer Sealab;Earth:Uranus;",
			"Drudge Brazer;None;Grineer Shipyard:Grineer Asteroid;None;",
			"Drudge Foreman;None;Grineer Shipyard:Grineer Asteroid;None;",
			"Drudge Scrapper;None;Grineer Shipyard:Grineer Asteroid;None;",
			"Eidolon Lure;None;Plains of Eidolon;Earth;",
			"Elite Arid Lancer;None;Grineer Settlement;Mars;",
			"Elite Exo Cutter;Empyrean;Free Space;Veil Proxima;",
			"Elite Exo Flak;Empyrean;Free Space;Veil Proxima;",
			"Elite Exo Gokstad Crewship;Empyrean;Free Space;Veil Proxima;",
			"Elite Exo Outrider;Empyrean;Free Space;Veil Proxima;",
			"Elite Exo Ramsled;Empyrean;Free Space;Veil Proxima;",
			"Elite Exo Taktis;Empyrean;Free Space;Veil Proxima;",
			"Elite Frontier Lancer;None;Grineer Forest;Earth;",
			"Elite Gyre Cutter;Empyrean;Free Space;Saturn Proxima;",
			"Elite Gyre Flak;Empyrean;Free Space;Saturn Proxima;",
			"Elite Gyre Outrider;Empyrean;Free Space;Saturn Proxima;",
			"Elite Gyre Taktis;Empyrean;Free Space;Saturn Proxima;",
			"Elite Kosma Cutter;Empyrean;Free Space;Earth Proxima;",
			"Elite Kosma Flak;Empyrean;Free Space;Earth Proxima;",
			"Elite Kosma Outrider;Empyrean;Free Space;Earth Proxima;",
			"Elite Kosma Taktis;Empyrean;Free Space;Earth Proxima;",
			"Eviscerator;None;Grineer Asteroid:Grineer Galleon:Grineer Shipyard:Orokin Moon;Mercury:Ceres:Saturn:Sedna:Lua;",
			"Executioner Dhurnam;Rathuum;None;Sedna;",
			"Executioner Dok Thul;Rathuum;None;Sedna;",
			"Executioner Garesh;Rathuum;None;Sedna;",
			"Executioner Gorth;Rathuum;None;Sedna;",
			"Executioner Harkonar;Rathuum;None;Sedna;",
			"Executioner Nok;Rathuum;None;Sedna;",
			"Executioner Reth;Rathuum;None;Sedna;",
			"Executioner Vay Molta;Rathuum;None;Sedna;",
			"Executioner Zura;Rathuum;None;Sedna;",
			"Exo Butcher;Empyrean;None;Veil Proxima;",
			"Exo Cutter;Empyrean;Free Space;Veil Proxima;",
			"Exo Elite Lancer;Empyrean;None;Veil Proxima;",
			"Exo Eviscerator;Empyrean;None;Veil Proxima;",
			"Exo Flak;Empyrean;Free Space;Veil Proxima;",
			"Exo Gokstad Crewship;Empyrean;Free Space;Veil Proxima;",
			"Exo Gokstad Officer;Empyrean;None;Veil Proxima;",
			"Exo Gokstad Pilot;Empyrean;None;Veil Proxima;",
			"Exo Outrider;Empyrean;Free Space;Veil Proxima;",
			"Exo Raider;Empyrean;None;Veil Proxima;",
			"Exo Raider Carver;Empyrean;None;Veil Proxima;",
			"Exo Raider Eviscerator;Empyrean;None;Veil Proxima;",
			"Exo Ramsled;Empyrean;Free Space;Veil Proxima;",
			"Exo Roller Sentry;Empyrean;None;Veil Proxima;",
			"Exo Supressor;Empyrean;None;Veil Proxima;",
			"Exo Taktis;Empyrean;Free Space;Veil Proxima;",
			"Fortress Scanner;None;Grineer Asteroid Fortress;Kuva Fortress;",
			"Frontier Butcher;None;Grineer Forest;Earth;",
			"Frontier Eviscerator;None;Grineer Forest;Earth;",
			"Frontier Heavy Gunner;None;Grineer Forest;Earth;",
			"Frontier Hellion;None;Grineer Forest;Earth;",
			"Frontier Lancer;None;Grineer Forest;Earth;",
			"Frontier Regulator;None;Grineer Forest;Earth;",
			"Frontier Seeker;None;Grineer Forest;Earth;",
			"Frontier Trooper;None;Grineer Forest;Earth;",
			"Garv;Necralisk Bounty;Cambion Drift;Deimos;",
			"General Sargas Ruk;Assassination:Tethys;Grineer Galleon;Saturn;",
			"Ghoul Auger;Cetus Bounty;Plains of Eidolon;Earth;",
			"Ghoul Auger Alpha;Cetus Bounty;Plains of Eidolon;Earth;",
			"Ghoul Devourer;Cetus Bounty;Plains of Eidolon;Earth;",
			"Ghoul Expired;Cetus Bounty;Plains of Eidolon;Earth;",
			"Ghoul Rictus;Cetus Bounty;Plains of Eidolon;Earth;",
			"Ghoul Rictus Alpha;Cetus Bounty;Plains of Eidolon;Earth;",
			"Ghoul Target;Cetus Bounty;Plains of Eidolon;Earth;",
			"Glacik Commander;Empyrean;Grineer Asteroid;Saturn Proxima;",
			"Grineer Power Carrier;Excavation;Grineer Forest;Earth;",
			"Grineer Queens;The War Within;None;Kuva Fortress;",
			"Grineer Target;Capture;None;None;",
			"Grineer Warden;Rescue;None;None;",
			"Guardsman;None;Grineer Shipyard;None;",
			"Gyre Butcher;Empyrean;None;Saturn Proxima;",
			"Gyre Cutter;Empyrean;Free Space;Saturn Proxima;",
			"Gyre Elite Lancer;Empyrean;None;Saturn Proxima;",
			"Gyre Eviscerator;Empyrean;None;Saturn Proxima;",
			"Gyre Flak;Empyrean;Free Space;Saturn Proxima;",
			"Gyre Gokstad Crewship;Empyrean;Free Space;Saturn Proxima;",
			"Gyre Gokstad Officer;Empyrean;None;Saturn Proxima;",
			"Gyre Gokstad Pilot;Empyrean;None;Saturn Proxima;",
			"Gyre Outrider;Empyrean;Free Space;Saturn Proxima;",
			"Gyre Raider;Empyrean;None;Saturn Proxima;",
			"Gyre Raider Carver;Empyrean;None;Saturn Proxima;",
			"Gyre Raider Eviscerator;Empyrean;None;Saturn Proxima;",
			"Gyre Ramsled;Empyrean;Free Space;Saturn Proxima;",
			"Gyre Roller Sentry;Empyrean;None;Saturn Proxima;",
			"Gyre Supressor;Empyrean;None;Saturn Proxima;",
			"Gyre Taktis;Empyrean;Free Space;Saturn Proxima;",
			"Hellion Dargyn;Archwing (Mission);None;None;",
			"Hellion Power Carrier;Excavation;None;None;",
			"Kavor Defector;Defection;Grineer Asteroid:Grineer Galleon:Infested Ship;Phobos:Saturn:Neptune;",
			"Kela De Thaym;Assassination:Merrow;Grineer Asteroid;Sedna;",
			"Kosma Butcher;Empyrean;None;Earth Proxima;",
			"Kosma Cutter;Empyrean;Free Space;Earth Proxima;",
			"Kosma Elite Lancer;Empyrean;None;Earth Proxima;",
			"Kosma Eviscerator;Empyrean;None;Earth Proxima;",
			"Kosma Flak;Empyrean;Free Space;Earth Proxima;",
			"Kosma Gokstad Crewship;Empyrean;Free Space;Earth Proxima;",
			"Kosma Gokstad Officer;Empyrean;None;Earth Proxima;",
			"Kosma Gokstad Pilot;Empyrean;None;Earth Proxima;",
			"Kosma Outrider;Empyrean;Free Space;Earth Proxima;",
			"Kosma Raider;Empyrean;None;Earth Proxima;",
			"Kosma Raider Carver;Empyrean;None;Earth Proxima;",
			"Kosma Raider Eviscerator;Empyrean;None;Earth Proxima;",
			"Kosma Ramsled;Empyrean;Free Space;Earth Proxima;",
			"Kosma Roller Sentry;Empyrean;None;Earth Proxima;",
			"Kosma Supressor;Empyrean;None;Earth Proxima;",
			"Kosma Taktis;Empyrean;Free Space;Earth Proxima;",
			"Kuva;Kuva Siphon;None;None;",
			"Kuva Ballista;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Bombard;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Butcher;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Dargyn;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Drahk;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Drahk Master;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Elite Lancer;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Elite Lancer Eximus;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Eviscerator;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Flameblade;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Guardian;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Heavy Gunner;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Hellion;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Hyekka;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Hyekka Master;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Jester;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Lancer;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Napalm;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Powerclaw;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Roller;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Scorch;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Scorpion;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Seeker;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Shield Lancer;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Kuva Siphon;Kuva Siphon;None;Any near Kuva Fortress;",
			"Kuva Trokarian;None;Zariman (Tileset);Zariman Ten Zero;",
			"Kuva Trooper;None;Grineer Asteroid Fortress:Zariman (Tileset);Kuva Fortress:Zariman Ten Zero;",
			"Lancer Dreg;Archwing (Mission);None;None;",
			"Lancer Survivor;Necralisk Bounty;Cambion Drift;Deimos;",
			"Lektro Commander;None;Grineer Asteroid;None;",
			"Lieutenant Lech Kril;Assassination:War (Node):Exta;Grineer Settlement:Grineer Shipyard;Mars:Ceres;",
			"Manic Bombard;None;Grineer Sealab;Uranus;",
			"Mordda Turret;None;Plains of Eidolon;Earth;",
			"Nightwatch Carrier;Excavation;None;None;",
			"Ogma;Archwing (Mission);None;None;",
			"Ogma Elite;Eyes of Blight;None;None;",
			"Orbital Strike Drone;Assassination:Oro;Grineer Forest;Earth;",
			"Plains Commander;Cetus Bounty;Plains of Eidolon;Earth;",
			"Propaganda Drone;Assassination:Oro;Grineer Forest;Earth;",
			"Prosecutor;None;Grineer Shipyard;None;",
			"Pyr Captain;Empyrean;Grineer Galleon;Earth Proxima:Veil Proxima;",
			"Recon Commander;Cetus Bounty;Plains of Eidolon;Earth;",
			"Sensor Regulator;Spy;None;None;",
			"Senta Turret (Kuva Fortress);None;Grineer Asteroid Fortress;Kuva Fortress;",
			"Shield Dargyn;Archwing (Mission);None;None;",
			"Shield-Hellion Dargyn;Archwing (Mission);None;Uranus;",
			"Shock Draga;None;Grineer Sealab;None;",
			"Sikula;None;Grineer Sealab;None;",
			"Sprag;Orokin Sabotage:Formido:Stribog;None;None;",
			"Temporal Dreg;Archwing (Mission);None;None;",
			"Trooper Survivor;Necralisk Bounty;Cambion Drift;Deimos;",
			"Tusk Ballista;None;Plains of Eidolon;Earth;",
			"Tusk Bolkor;None;Plains of Eidolon;Earth;",
			"Tusk Bombard;None;Plains of Eidolon;Earth;",
			"Tusk Butcher;None;Plains of Eidolon;Earth;",
			"Tusk Carabus;None;Plains of Eidolon;Earth;",
			"Tusk Command Dargyn;Cetus Bounty;Plains of Eidolon;Earth;",
			"Tusk Dargyn;None;Plains of Eidolon;Earth;",
			"Tusk Elite Lancer;None;Plains of Eidolon;Earth;",
			"Tusk Eviscerator;None;Plains of Eidolon;Earth;",
			"Tusk Firbolg;None;Plains of Eidolon;Earth;",
			"Tusk Flameblade;None;Plains of Eidolon;Earth;",
			"Tusk Heavy Gunner;None;Plains of Eidolon;Earth;",
			"Tusk Hellion;None;Plains of Eidolon;Earth;",
			"Tusk Lancer;None;Plains of Eidolon;Earth;",
			"Tusk Mortar Bombard;None;Plains of Eidolon;Earth;",
			"Tusk Napalm;None;Plains of Eidolon;Earth;",
			"Tusk Ogma;None;Plains of Eidolon;Earth;",
			"Tusk Predator;None;Plains of Eidolon;Earth;",
			"Tusk Reaver;None;Plains of Eidolon;Earth;",
			"Tusk Roller;None;Plains of Eidolon;Earth;",
			"Tusk Seeker;None;Plains of Eidolon;Earth;",
			"Tusk Seeker Drone;None;Plains of Eidolon;Earth;",
			"Tusk Shield Dargyn;None;Plains of Eidolon;Earth;",
			"Tusk Shield Lancer;None;Plains of Eidolon;Earth;",
			"Tusk Target;Cetus Bounty;Plains of Eidolon;Earth;",
			"Tusk Thumper;None;Plains of Eidolon;Earth;",
			"Tusk Thumper Bull;None;Plains of Eidolon;Earth;",
			"Tusk Thumper Doma;None;Plains of Eidolon;Earth;",
			"Tusk Trooper;None;Plains of Eidolon;Earth;",
			"Tyl Regor;Assassination:Titania (Node);Grineer Sealab;Uranus;",
			"Vay Hek Terra Frame;Assassination:Oro;Grineer Forest;Earth;",
			"Ven'kra Tel;Orokin Sabotage:Formido:Stribog;None;None;",
			"Vruush Turret;None;Plains of Eidolon;Earth;",
			"Zeplen;Fomorian Sabotage;Free Space;None;","Ancient Disruptor;None;None;Mercury:Venus:Earth:Mars:Jupiter:Saturn:Uranus:Neptune:Pluto:Ceres:Eris:Sedna:Europa:Phobos:Deimos;",
			"Ancient Protector;None;None;Mercury:Venus:Earth:Mars:Jupiter:Saturn:Uranus:Neptune:Pluto:Ceres:Eris:Sedna:Europa:Phobos:Deimos;",
			"Arcane Boiler;Stolen Dreams;Orokin Derelict;None;",
			"Attack Mutalist;Jordas Golem Assassanation;None;None;",
			"Basal Diploid;None;Cambion Drift;Deimos;",
			"Basal Diploid Rex;Necralisk Bounty;Cambion Drift;Deimos;",
			"Blighted Maggot;Arcana Isolation Vault Bounty;Cambion Drift;Deimos;",
			"Carrion Charger;Defection;Grineer Asteroid:Grineer Galleon:Infested Ship;Phobos:Saturn:Neptune;",
			"Chroma;The New Strange;None;None;",
			"Deimos Ancient Healer;None;Cambion Drift;Deimos;",
			"Deimos Brood Mother;None;Cambion Drift;Deimos;",
			"Deimos Carnis;None;Cambion Drift;Deimos;",
			"Deimos Carnis Rex;Necralisk Bounty;Cambion Drift;Deimos;",
			"Deimos Charger;None;Cambion Drift;Deimos;",
			"Deimos Genetrix;None;Cambion Drift;Deimos;",
			"Deimos Juggernaut;None;Cambion Drift;Deimos;",
			"Deimos Jugulus;None;Cambion Drift;Deimos;",
			"Deimos Jugulus Rex;Necralisk Bounty;Cambion Drift;Deimos;",
			"Deimos Leaper;None;Cambion Drift;Deimos;",
			"Deimos Leaping Thrasher;None;Cambion Drift;Deimos;",
			"Deimos Mutalist Osprey Carrier;Excavation;Cambion Drift;Deimos;",
			"Deimos Runner;None;Cambion Drift;Deimos;",
			"Deimos Saxum;None;Cambion Drift;Deimos;",
			"Deimos Saxum Rex;Necralisk Bounty;Cambion Drift;Deimos;",
			"Deimos Swarm Mutalist MOA;Shrine Defence;None;Earth;",
			"Deimos Tendril Drone;None;Cambion Drift;Deimos;",
			"Deimos Therid;None;Cambion Drift;Deimos;",
			"Deimos Undying Flyer;Shrine Defence;None;Earth;",
			"Deimos Venin Mutalist;None;Cambion Drift;Deimos;",
			"Demolisher Boiler;Disruption;Grineer Galleon;Uranus;",
			"Demolisher Charger;Disruption;Grineer Galleon;Uranus;",
			"Demolisher Juggernaut;Disruption;Grineer Galleon;Uranus;",
			"Demolisher Thrasher;Disruption;Grineer Galleon;Uranus;",
			"Feral Diploid;None;Cambion Drift;Deimos;",
			"Feral Diploid Rex;Necralisk Bounty;Cambion Drift;Deimos;",
			"Frozen Infested Hive;Hive:Hidden Messages:Patient Zero;Infested Ship;Eris;",
			"Gas Infested Hive;Hive:Hidden Messages:Patient Zero;Infested Ship;Eris;",
			"Hemocyte;Operation: Plague Star;Plains of Eidolon;Earth;",
			"Infested Mesa;Patient Zero;None;None;",
			"Infested Oni;Shrine Defense;None;Earth;",
			"Jack O'Naut;Hallowed Nightmares;None;None;",
			"Jordas Golem;Jordas Golem Assassinate;None;Eris;",
			"Juggernaut Behemoth;Assassination:Jordas Golem Assassinate;Infested Ship;Eris;",
			"Lancing Infested Hive;Hive:Hidden Messages:Patient Zero;Infested Ship;Eris;",
			"Leaping Thrasher;None;Orokin Derelict;Deimos;",
			"Lephantis;Assassination:Magnacidium;Orokin Derelict;Deimos;",
			"Mitosid;None;Cambion Drift;Deimos;",
			"Mitosid Rex;Necralisk Bounty;Cambion Drift;Deimos;",
			"Mutalist Alad V;Assassination:Mutalist Alad V Assassination;Infested Ship;Eris;",
			"Mutalist Lightning Carrier;Jordas Golem Assassanation;None;None;",
			"Mutalist Osprey Carrier;Excavation;None;None;",
			"Mutalist Toxic Carrier;Jordas Golem Assassanation;None;None;",
			"Phorid;Assassination:Invasion;Grineer Asteroid;None;",
			"Polyp-Hog Juggernaut;Necralisk Bounty;Cambion Drift;Deimos;",
			"Pulsing Infested Hive;Hive:Hidden Messages:Patient Zero;Infested Ship;Eris;",
			"Security Infested Hive;Hive:Hidden Messages:Patient Zero;Infested Ship;Eris;",
			"Stabilization Infested Hive;Hive:Hidden Messages:Patient Zero;Infested Ship;Eris;",
			"Undying Flyer;None;Cambion Drift;Deimos;",
			"Venin Mutalist;Defection;None;None;",
			"Zealoid Bastion;Assassination:Exequias;Orokin Derelict;Deimos;",
			"Zealoid Prelate;Assassination:Exequias;Orokin Derelict;Deimos;",
			"Zealot Baptizer;Nightwave/Series 2;None;None;",
			"Zealot Herald;Nightwave/Series 2;None;None;",
			"Zealot Proselytizer;Nightwave/Series 2;None;None;","Deimos Rogue Bonewidow;Cambion Drift;Cambion Drift;Deimos;",
			"Demolisher Bonewidow;Disruption;Albrecht's Laboratories;Deimos;",
			"Demolisher Voidrig;Disruption;Albrecht's Laboratories;Deimos;",
			"Elementa Arcocanid;Alchemy;Albrecht's Laboratories;Deimos;",
			"Elementa Culverin;Alchemy;Albrecht's Laboratories;Deimos;",
			"Gruzzling;None;Albrecht's Laboratories;Deimos;",
			"Hurling Fragment;None;Albrecht's Laboratories;Deimos;",
			"Lumbering Fragment;None;Albrecht's Laboratories;Deimos;",
			"Mocking Whisper;None;Albrecht's Laboratories;Deimos;",
			"Rogue Arcocanid;None;Albrecht's Laboratories;Deimos;",
			"Rogue Bonewidow;None;Albrecht's Laboratories;Deimos;",
			"Rogue Culverin;None;Albrecht's Laboratories;Deimos;",
			"Rogue Voidrig;None;Albrecht's Laboratories;Deimos;",
			"Rogue Voidrig (Deimos);Isolation Vault;Cambion Drift;Deimos;",
			"Rupturing Fragment;None;Albrecht's Laboratories;Deimos;",
			"Scathing Whisper;None;Albrecht's Laboratories;Deimos;",
			"Shuffling Fragment;None;Albrecht's Laboratories;Deimos;",
			"The Anatomizer;None;Albrecht's Laboratories;Deimos;",
			"The Fragmented;Assassination;Albrecht's Laboratories;Deimos;",
			"The Hollow Vein;None;Albrecht's Laboratories;Deimos;",
			"The Severed Warden;None;Albrecht's Laboratories;Deimos;","Archon Amar;Archon Hunt;None;Mars;",
			"Archon Boreal;Archon Hunt;None;Earth;",
			"Archon Nira;Archon Hunt;None;Jupiter;",
			"Narmer Buzzard Dropship;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Ballista;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Bolkor;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Bombard;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Coildrive;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Condor Dropship;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Commander;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Corpus Tech;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Crewman;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Deacon;Archon Hunt;None;Earth:Mars:Jupiter;",
			"Narmer Dera MOA;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Detron Crewman;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Disc MOA;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Firbolg;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Flameblade;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Geminex MOA;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Glaxion MOA;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Heavy Gunner;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Hellion;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Jailer;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Lancer;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Leech Osprey;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Militant;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Mine Osprey;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Napalm;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Nullifier Crewman;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Powerfist;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Prod Crewman;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Raknoid;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Sapping Osprey;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Scorch;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Scorpion;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Shield Lancer;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Shield Osprey;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Sniper Crewman;Narmer Bounty;Orb Vallis;Venus;",
			"Narmer Thumper Doma;Narmer Bounty;Plains of Eidolon;Earth;",
			"Narmer Trooper;Narmer Bounty;Plains of Eidolon;Earth;","Scaldra Jaeger;None;None;Höllvania;",
			"Scaldra Flayer;None;None;Höllvania;",
			"Scaldra Barbican;None;None;Höllvania;",
			"Scaldra Harbinger;None;None;Höllvania;",
			"Scaldra Dedicant;None;None;Höllvania;",
			"Scaldra Eradicator;None;None;Höllvania;",
			"Scaldra TI-92;None;None;Höllvania;",
			"H-09 Apex;Assassination:Victory Plaza;None;Höllvania;",
			"H-09 Efervon Tank;Assassination:Victory Plaza;None;Höllvania;","Aerolyst;Orphix (Mission):Archon Hunt;Murex:Grineer Forest;None;",
			"Anu Brachiolyst;Scarlet Spear:The New War;None;None;",
			"Anu Interference Drone;Scarlet Spear:The New War;None;None;",
			"Anu Mantalyst;Scarlet Spear:The New War;None;None;",
			"Anu Pyrolyst;Scarlet Spear;None;None;",
			"Anu Symbilyst;Scarlet Spear;None;None;",
			"Brachiolyst;Orphix (Mission);Murex;Veil Proxima;",
			"Choralyst;Orphix (Mission);Corpus Ship;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Condrix;Operation: Scarlet Spear;Grineer Forest;Earth;",
			"Decaying Battalyst;Octavia's Anthem;Orokin Tower;Void;",
			"Decaying Conculyst;Octavia's Anthem;Orokin Tower;Void;",
			"Eidolon Gantulyst;Cetus Bounty:Free Roam;Plains of Eidolon;Earth;",
			"Eidolon Hydrolyst;Cetus Bounty:Free Roam;Plains of Eidolon;Earth;",
			"Eidolon Teralyst;Cetus Bounty:Free Roam;Plains of Eidolon;Earth;",
			"Eidolon Vomvalyst;None;Plains of Eidolon:Murex;Earth:Veil Proxima;",
			"Eradicyst;Octavia's Anthem;None;None;",
			"Gyrix;Empyrean;None;None;",
			"Ionyx;Empyrean;None;None;",
			"Mimic;The Sacrifice;Murex;Veil Proxima;",
			"Oculyst;None;Grineer Sealab:Orokin Moon;Uranus:Lua;",
			"Orphix;Orphix (Mission);Corpus Ship;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Ropalolyst;Assassination:The Ropalolyst;Corpus Gas City;Jupiter;",
			"Splintrix;Scarlet Spear;None;None;",
			"Summulyst;Orphix (Mission);Corpus Ship;Venus Proxima:Neptune Proxima:Pluto Proxima:Veil Proxima;",
			"Typholyst;The New War;None;None;",
			"Tyro Battalyst;Archon Hunt:Sentient Anomaly;Murex;Veil Proxima;",
			"Tyro Conculyst;Archon Hunt;None;None;","Legacyte;Legacyte Harvest:Köbinn West;None;Höllvania;",
			"Techrot Babau;None;None;Höllvania;",
			"Techrot Galliflex;None;None;Höllvania;",
			"Techrot Matmas;None;None;Höllvania;",
			"Techrot Miasmite;None;None;Höllvania;",
			"Techrot Obsolyte;None;None;Höllvania;",
			"Techrot Scaart;Faceoff:Lower Vehrvod:Vehrvod District;None;Höllvania;",
			"Techrot Skuzzi;None;None;Höllvania;",
			"Techrot Volatile Galliflex;None;None;Höllvania;",
			"H-09 Apex (Techrot);Assassination:Victory Plaza;None;Höllvania;",
			"H-09 Efervon Tank (Techrot);Assassination:Victory Plaza;None;Höllvania;","Alpine Monitor Sawgaw;None;Orb Vallis;Venus;",
			"Amethyst Nexifera;None;Cambion Drift;Deimos;",
			"Arbitration Shield Drone;Arbitrations;None;None;",
			"Ashen Kuaka;None;Plains of Eidolon;Earth;",
			"Bau Vasca Kavat;None;Plains of Eidolon;Earth;",
			"Black-Banded Bolarola;None;Orb Vallis;Venus;",
			"Brindle Kubrodon;None;Orb Vallis;Venus;",
			"Burrowing Cryptilex;None;Cambion Drift;Deimos;",
			"Caustic Cryptilex;None;Cambion Drift;Deimos;",
			"Clem;A Man of Few Words:Help Clem;None;None;",
			"Coastal Mergoo;None;Plains of Eidolon;Earth;",
			"Common Avichaea;None;Cambion Drift;Deimos;",
			"Common Condroc;None;Plains of Eidolon;Earth;",
			"Crescent Vulpaphyla;None;Cambion Drift;Deimos;",
			"Dappled Horrasque;None;Orb Vallis;Venus;",
			"Darvo;Ties That Bind:Vor's Prize:Relay;None;None;",
			"Dax Arcus;None;None;Duviri;",
			"Dax Equitem;None;None;Duviri;",
			"Dax Gladius;None;None;Duviri;",
			"Dax Herald;None;None;Duviri;",
			"Dax Malleus;None;None;Duviri;",
			"Deep Archimedea Void Angel;Deep Archimedea;Albrecht's Laboratories;Deimos;",
			"Delicate Pobber;None;Orb Vallis;Venus;",
			"Desert Skate;None;Grineer Settlement;Mars;",
			"Dusky-Headed Virmink;None;Orb Vallis;Venus;",
			"Eclipse Thrax Centurion;Yuvarium;None;None;",
			"Emperor Condroc;None;Plains of Eidolon;Earth;",
			"Fire-Veined Stover;None;Orb Vallis;Venus;",
			"Flossy Sawgaw;None;Orb Vallis;Venus;",
			"Frogmouthed Sawgaw;None;Orb Vallis;Venus;",
			"Fuming Dax Stover;None;Orb Vallis;Venus;",
			"Ghost Kuaka;None;Plains of Eidolon;Earth;",
			"Ghoul Expired Deserter;Cetus Bounty;Plains of Eidolon;Earth;",
			"Green Velocipod;None;Cambion Drift;Deimos;",
			"Hacked Drone;Cetus Bounty;Plains of Eidolon;Earth;",
			"Hollow Thrax Centurion (Duviri);Duviri:The Circuit;None;None;",
			"Hollow Thrax Centurion (Lua);Yuvarium;None;None;",
			"Hollow Thrax Legatus (Duviri);The Circuit;None;None;",
			"Hollow Thrax Legatus (Lua);Yuvarium;None;None;",
			"Horrasque Stormer;None;Orb Vallis;Venus;",
			"Howler Undazoa;None;Cambion Drift;Deimos;",
			"Kavat;None;Orokin Derelict;Deimos;",
			"Kubrodon Incarnadine;None;Orb Vallis;Venus;",
			"Kubrow;None;Grineer Forest;Earth;",
			"Kuva Injector;Defense;Grineer Asteroid Fortress;Kuva Fortress;",
			"Liminus;None;None;Duviri;",
			"Lua Thrax Legatus;Conjunction Survival;None;None;",
			"Medjay Predasite;None;Cambion Drift;Deimos;",
			"Necramite;?;Albrecht's Laboratories;Deimos;",
			"Nephil Vasca Kavat;None;Plains of Eidolon;Earth;",
			"Ostia Vasca Kavat;None;Plains of Eidolon;Earth;",
			"Panzer Vulpaphyla;None;Cambion Drift;Deimos;",
			"Pharaoh Predasite;None;Cambion Drift;Deimos;",
			"Plains Kuaka;None;Plains of Eidolon;Earth;",
			"Purple Velocipod;None;Cambion Drift;Deimos;",
			"Ravenous Void Angel;Void Armageddon;Zariman (Tileset);Zariman Ten Zero;",
			"Red-Crested Virmink;None;Orb Vallis;Venus;",
			"Rogue Condroc;None;Plains of Eidolon;Earth;",
			"Scarlet Nexifera;None;Cambion Drift;Deimos;",
			"Sentinel Stover;None;Orb Vallis;Venus;",
			"Septic Cryptilex;None;Cambion Drift;Deimos;",
			"Sly Vulpaphyla;None;Cambion Drift;Deimos;",
			"Splendid Mergoo;None;Plains of Eidolon;Earth;",
			"Sporule Avichaea;None;Cambion Drift;Deimos;",
			"Spotted Bolarola;None;Orb Vallis;Venus;",
			"Subterranean Pobber;None;Orb Vallis;Venus;",
			"Sunny Pobber;None;Orb Vallis;Venus;",
			"Swimmer Horrasque;None;Orb Vallis;Venus;",
			"Thorny Bolarola;None;Orb Vallis;Venus;",
			"Thrax Centurion;None;Zariman (Tileset);Zariman Ten Zero;",
			"Thrax Legatus;None;Zariman (Tileset);Zariman Ten Zero;",
			"Tomb Guardian;Sand of Inaros;Grineer Settlement;Mars;",
			"Tomb Protector;Sand of Inaros;Grineer Settlement;Mars;",
			"Tomb Protector Effigy;Sand of Inaros;Grineer Settlement;Mars;",
			"Umber Undazoa;None;Cambion Drift;Deimos;",
			"Vallis Kubrodon;None;Orb Vallis;Venus;",
			"Vaporous Undazoa;None;Cambion Drift;Deimos;",
			"Viridian Nexifera;None;Cambion Drift;Deimos;",
			"Viscid Avichaea;None;Cambion Drift;Deimos;",
			"Vitriol Necramite;?;Albrecht's Laboratories;Deimos;",
			"Vizier Predasite;None;Cambion Drift;Deimos;",
			"Void Angel;None;Zariman (Tileset);Zariman Ten Zero;",
			"White Velocipod;None;Cambion Drift;Deimos;",
			"White-Breasted Virmink;None;Orb Vallis;Venus;",
			"Wolf of Saturn Six;Nightwave/Series 1;None;None;",
			"Woodland Mergoo;None;Plains of Eidolon;Earth;"
		};
	
	
	private class EnemyLocation {
		String name = "";
		String missions = "";
		String tileSets = "";
		String planets = "";
		
		public EnemyLocation(String name, String missions, String tileSets, String planets) {
			this.name = name;
			this.missions = missions.trim();
			this.tileSets = tileSets.trim();
			this.planets = planets.trim();
		}
		
		
		public String toString() {
			String toReturn = " "+ name +" found ";
			if(!missions.equalsIgnoreCase("none")) {
				toReturn += " in "+ missions;
			}
			if(!tileSets.equalsIgnoreCase("none")) {
				toReturn += " within "+ tileSets;
			}
			if(!planets.equalsIgnoreCase("none")) {
				toReturn += " on "+ planets;
			}
			return toReturn;
		}
	}
}
